# Determining the Optimal Model and Hyperparameters for classifying Sklearn's Digits dataset.

This is my attempt at finding the best performining classifier along with the parameters for Sklearn's digits dataset. I will continuosly improve the model(s) over time, be it through adding classifiers or optimizing the exiting one(s)

## Importing the relavant libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
import xgboost as xgb
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix

from sklearn.datasets import load_digits

## Loading and Formating Data

In [3]:
digits = load_digits()

In [4]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
# Exploring the data

# plt.gray() 
# for i in range(4):
#    plt.matshow(digits.images[i])

In [6]:
#digits.target

In [7]:
# Putting the data into a data frame 

df = pd.DataFrame(digits.data)

df.head()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [8]:
df['target'] = digits.target

df.head(3)

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2

In [9]:
X = df.drop('target',axis='columns')

y = df.target

## Selecting The Best Model

In [19]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [10,20,50],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,10,20]
        }
    },
    'xgboost': {
        'model': xgb.XGBClassifier(objective = 'binary:logistic', missing = None, seed = 42),
        'params' : {
            'max_depth': [3, 2],
            'learning_rate': [0.1],
            'gamma': [0],
            'reg_lambda': [0],
            
        }
    },
    'multinomial': {
        'model': MultinomialNB(fit_prior=True, class_prior=None),
        'params' : {
            'alpha': [1,10,20]
        }
    },
    
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [0.1,1,15]
        }
    }
}

In [20]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

scores = []

for model_name, mp in model_params.items():
    
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    
    clf.fit(X, y)
    
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

,model,best_score,best_params
0,svm,0.947697,"{'C': 10, 'kernel': 'linear'}"
1,random_forest,0.923782,{'n_estimators': 20}
2,xgboost,0.924333,"{'gamma': 0, 'learning_rate': 0.1, 'max_depth'..."
3,multinomial,0.874246,{'alpha': 10}
4,logistic_regression,0.924342,{'C': 0.1}

In [21]:
df.iloc[2,2]

{'gamma': 0, 'learning_rate': 0.1, 'max_depth': 3, 'reg_lambda': 0}